### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ctallent**
deleted the "ck" from track. this is a test to see what happens.

### CODE REVIEW

**Review by Rio517 — COMMENTED** [review]
What are you trying to accomplish?  Check out the readme for details on staging/production.

**Comment by ctallent** [comment]
Hey Mario, I'm trying to make to make some changes to the website. Is this
a real message or automatically generated?

Thanks,

Chris

**Comment by Rio517** [comment]
I am not automatically generated.  You need to make sure you are editing
the production branch. As detailed in the readme, the master branch is
deployed to the staging environment.

**Comment by ctallent** [comment]
great, thanks Mario, I'm learning this as I go.

-Chris

**Comment by Rio517** [comment]
No problem. Let me know if you have any technical questions.  I don't 
mind the occasional 5-10 minute question.

-Mario

**Comment by ctallent** [comment]
cool, thanks Mario. I think I do have a question: How long does it usually
take before changes are visible on the website? I've been looking at it
this morning, and it seems that key language I tried to change yesterday on
the front page is still there...

Chris

**Pull request merged**
